package com.live.user.model;

public class RolePermission {
    /** serialVersionUID. */
    private static final long serialVersionUID =1493049839167L;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_permission.rid
     *
     * @mbg.generated Fri Oct 12 16:12:19 CST 2018
     */
    private Integer rid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_permission.pid
     *
     * @mbg.generated Fri Oct 12 16:12:19 CST 2018
     */
    private Integer pid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_permission.rid
     *
     * @return the value of role_permission.rid
     *
     * @mbg.generated Fri Oct 12 16:12:19 CST 2018
     */
    public Integer getRid() {
        return rid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_permission.rid
     *
     * @param rid the value for role_permission.rid
     *
     * @mbg.generated Fri Oct 12 16:12:19 CST 2018
     */
    public void setRid(Integer rid) {
        this.rid = rid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_permission.pid
     *
     * @return the value of role_permission.pid
     *
     * @mbg.generated Fri Oct 12 16:12:19 CST 2018
     */
    public Integer getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_permission.pid
     *
     * @param pid the value for role_permission.pid
     *
     * @mbg.generated Fri Oct 12 16:12:19 CST 2018
     */
    public void setPid(Integer pid) {
        this.pid = pid;
    }
}